-- Expand the model-facing content taxonomy from ten generic labels to a
-- broad evidence-aware vocabulary. Runtime validation remains authoritative;
-- this migration makes the same vocabulary discoverable through the tag API.

INSERT INTO tags (id, name, slug, parent_slug, description, usage_count, created_at)
SELECT gen_random_uuid(), seed.name, 'content/' || seed.slug, 'content', seed.description, 0, NOW()
FROM (VALUES
    ('Gameplay', 'gameplay', 'Video game play is visibly on screen.'),
    ('Facecam', 'facecam', 'Streamer camera is the primary visible subject.'),
    ('VTuber', 'vtuber', 'A virtual avatar is the primary visible host.'),
    ('Screen Share', 'screen-share', 'A desktop, browser, or application is being shared.'),
    ('Conversation', 'conversation', 'People are visibly talking together.'),
    ('Interview', 'interview', 'Host and guest interview setup.'),
    ('Podcast', 'podcast', 'Podcast or panel recording setup.'),
    ('Commentary', 'commentary', 'Commentator or analysis presentation.'),
    ('Reaction', 'reaction', 'A clearly visible reaction to content.'),
    ('Review', 'review', 'A product, game, or media review.'),
    ('Educational', 'educational', 'Teaching or explanatory content.'),
    ('Tutorial', 'tutorial', 'Step-by-step instructional content.'),
    ('Demonstration', 'demonstration', 'A process or technique being demonstrated.'),
    ('IRL', 'irl', 'Real-world people or places rather than gameplay.'),
    ('Event', 'event', 'Organized real-world live event or gathering.'),
    ('Crowd', 'crowd', 'A real-world audience or large group.'),
    ('Stage', 'stage', 'A real-world stage or live venue is visible.'),
    ('Charity', 'charity', 'Fundraising or charity stream.'),
    ('Music', 'music', 'Music is the primary subject.'),
    ('Music Performance', 'music-performance', 'Real-world live musical performance is visible.'),
    ('Singing', 'singing', 'A real person is visibly performing vocals.'),
    ('Instrument', 'instrument', 'A real musical instrument is being played.'),
    ('Dance', 'dance', 'Real-world dance performance or practice.'),
    ('Creative', 'creative', 'Real-world creative work is the primary subject.'),
    ('Art', 'art', 'Real-world visual art creation or presentation.'),
    ('Drawing', 'drawing', 'Real-world drawing, painting, or illustration in progress.'),
    ('Cosplay', 'cosplay', 'A real person wears a character costume.'),
    ('Cooking', 'cooking', 'Meal preparation or cooking.'),
    ('Baking', 'baking', 'Baking or pastry preparation.'),
    ('Crafting', 'crafting', 'Hands-on craft work.'),
    ('Maker', 'maker', 'Building or repairing a physical project.'),
    ('Coding', 'coding', 'Software development or code is visibly central.'),
    ('Fitness', 'fitness', 'Real-world exercise or workout activity.'),
    ('Sports', 'sports', 'Real-world athletic activity.'),
    ('Travel', 'travel', 'Real-world travel destination or transit experience.'),
    ('Outdoors', 'outdoors', 'Real-world outdoor activity or natural setting.'),
    ('Animals', 'animals', 'A real animal is a central visible subject.'),
    ('Unboxing', 'unboxing', 'A product package is being opened.'),
    ('Pack Opening', 'pack-opening', 'A digital card or loot pack is being opened.'),
    ('Esports', 'esports', 'Organized competitive gaming.'),
    ('Tournament', 'tournament', 'Bracketed or organized competition.'),
    ('Ranked', 'ranked', 'Ranked or ladder gameplay.'),
    ('Casual Play', 'casual-play', 'Non-competitive casual gameplay.'),
    ('Multiplayer', 'multiplayer', 'Multiple human players are involved.'),
    ('Cooperative', 'cooperative', 'Players are cooperating toward a goal.'),
    ('PvP', 'pvp', 'Player-versus-player action.'),
    ('PvE', 'pve', 'Players face computer-controlled enemies.'),
    ('Boss Fight', 'boss-fight', 'A boss encounter is visibly underway.'),
    ('Puzzle', 'puzzle', 'Puzzle solving is central.'),
    ('Exploration', 'exploration', 'World or level exploration is central.'),
    ('Building', 'building', 'In-game construction is central.'),
    ('Roleplay', 'roleplay', 'Roleplay performance or roleplay server.'),
    ('Simulation', 'simulation', 'Simulation gameplay.'),
    ('Racing Game', 'racing-game', 'Vehicle racing gameplay.'),
    ('Fighting Game', 'fighting-game', 'One-on-one or arena fighting gameplay.'),
    ('Sports Game', 'sports-game', 'Sports video game gameplay.'),
    ('Strategy Game', 'strategy-game', 'Strategy game interface or play.'),
    ('Horror Game', 'horror-game', 'Horror game imagery or context.'),
    ('Retro Game', 'retro-game', 'Retro or classic game play.'),
    ('Shooter Game', 'shooter-game', 'First-person or third-person shooter gameplay.'),
    ('MOBA', 'moba', 'Multiplayer online battle arena gameplay.'),
    ('Battle Royale', 'battle-royale', 'Battle royale gameplay.'),
    ('Survival Game', 'survival-game', 'Survival-focused gameplay.'),
    ('Sandbox Game', 'sandbox-game', 'Open-ended sandbox gameplay.'),
    ('Card Game', 'card-game', 'Digital or physical card game play.'),
    ('Cutscene', 'cutscene', 'A narrative game cutscene is visibly playing.'),
    ('Ace', 'ace', 'One player eliminates the opposing team.'),
    ('Clutch', 'clutch', 'A high-pressure play reverses likely defeat.'),
    ('Victory', 'victory', 'A win or victory is explicitly evidenced.'),
    ('Defeat', 'defeat', 'A loss or defeat is explicitly evidenced.'),
    ('Comeback', 'comeback', 'A recovery from a losing position.'),
    ('Close Call', 'close-call', 'A narrowly avoided failure or defeat.'),
    ('Elimination', 'elimination', 'A player or opponent is eliminated.'),
    ('Team Wipe', 'team-wipe', 'An entire opposing team is eliminated.'),
    ('Speedrun', 'speedrun', 'Timed speedrun attempt or route.'),
    ('Record', 'record', 'A record result is explicitly established.'),
    ('Personal Best', 'personal-best', 'A personal-best result is established.'),
    ('Boss Kill', 'boss-kill', 'A boss is visibly or explicitly defeated.'),
    ('Jump Scare', 'jump-scare', 'A sudden scare and reaction are evidenced.'),
    ('Trick Shot', 'trick-shot', 'An intentionally difficult stylized shot succeeds.'),
    ('Achievement', 'achievement', 'An achievement or milestone is reached.'),
    ('Discovery', 'discovery', 'A new location, item, or fact is discovered.'),
    ('Challenge', 'challenge', 'A named challenge attempt.'),
    ('Reveal', 'reveal', 'A result, item, or announcement is revealed.'),
    ('Celebration', 'celebration', 'Visible celebration of an evidenced event.'),
    ('Fail', 'fail', 'An attempted action clearly fails.'),
    ('Bug', 'bug', 'A software or game defect is evidenced.'),
    ('Lucky', 'lucky', 'An outcome depends on clearly unusual luck.'),
    ('Highlight', 'highlight', 'A single standout moment.'),
    ('Highlights', 'highlights', 'A compilation or collection of standout moments.'),
    ('Funny', 'funny', 'Clearly comedic content, not merely a playful title.'),
    ('Wholesome', 'wholesome', 'Clearly warm or uplifting interaction.'),
    ('Emotional', 'emotional', 'Strong visible emotion with supporting context.'),
    ('Surprise', 'surprise', 'Clear visible surprise or astonishment.'),
    ('Rage', 'rage', 'Clear intense anger, not neutral concentration.'),
    ('Scary', 'scary', 'Frightening content or a fear response.'),
    ('Insane', 'insane', 'An exceptionally extreme moment.'),
    ('Toxic', 'toxic', 'Explicitly abusive or hostile conduct.'),
    ('Epic', 'epic', 'An unusually grand or dramatic moment.'),
    ('Beginner', 'noob', 'Clearly beginner-oriented play or instruction.'),
    ('Professional', 'pro', 'Verified professional-level context.')
) AS seed(name, slug, description)
ON CONFLICT (slug) DO NOTHING;
